preferred_syntax = :scss # or :sass
http_path = '/'
css_dir = 'css'
sass_dir = 'scss'
images_dir = 'images'
javascripts_dir = 'js'
relative_assets = true
line_comments = false # or true
output_style = :expanded # :nested, :expanded, :compact, or :compressed.
environment = :development # :development can also be :production